/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portapapeles;

import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author David Freyre Muñoz
 */
public class frmPrincipal extends javax.swing.JFrame {

   
    public frmPrincipal() {
        initComponents();
    }

    public JButton getBtnCopy() {
        return btnCopy;
    }

    public JButton getBtnCut() {
        return btnCut;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnPaste() {
        return btnPaste;
    }

    public JTextArea getTxtArea() {
        return txtArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnCopy = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        btnCut = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 36, 290, 290));

        btnCopy.setText("Copiar");
        jPanel1.add(btnCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 70, -1, -1));

        btnPaste.setText("Pegar");
        jPanel1.add(btnPaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 119, -1, -1));

        btnCut.setText("Cortar");
        jPanel1.add(btnCut, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 168, -1, -1));

        btnExit.setText("Salir");
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnCut;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPaste;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
